#!/bin/bash

set -eu

DIR="${1}"

cd "${DIR}"

rm -f Release Package.gz Sources.gz

MY_ARCH=`dpkg --print-architecture`

apt-ftparchive packages . > Packages
apt-ftparchive sources . > Sources
apt-ftparchive contents . > Contents-${MY_ARCH}

for file in Packages Sources Contents-${MY_ARCH} ; do
	bzip2 -f -k ${file}
done

apt-ftparchive release . > Release

release_temp=`tempfile`
chmod 777 ${release_temp}
LANG=C sudo -u masa gpg --armor --detach-sign --yes --output ${release_temp} ./Release
cp ${release_temp} ./Release.gpg
